n = int(input('Digite um número para ver sua tabuada: '))
print('-'*12)
print('{} x {:2} = {}'.format(n, 1, n*1))
print('{} x {:2} = {}'.format(n, 2, n*2))
print('{} x {:2} = {}'.format(n, 3, n*3))
print('{} x  {} = {}'.format(n, 4, n*4))
print('{} x  {} = {}'.format(n, 5, n*5))
print((n), 'x  6 =', (n*6))
print((n), 'x  7 =', (n*7))
print((n), 'x  8 =', (n*8))
print((n), 'x  9 =', (n*9))
print((n), 'x 10 =', (n*10))
print('-'*12)